# 选择一个基础镜像，这里我们使用官方的 Python 3.11 镜像
FROM registry.cn-shanghai.aliyuncs.com/jqy-common/python311-tmux:latest

# 设置工作目录为 /app
WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai PYTHONPATH=/app/cal_code

# 复制当前目录中的所有文件到容器的 /app/cal_code 目录
COPY /scripts /app/cal_code

# 安装 Python 依赖
# 假设你的依赖列表在 requirements.txt 文件中
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    sed -i 's|deb.debian.org|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list.d/debian.sources \
    && sed -i 's|security.debian.org|mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list.d/debian.sources \
    && apt update -y\
    && apt-get install -y cron
RUN --mount=type=cache,target=/root/.cache pip install -r cal_code/requirements.txt


# 清理apt缓存，以减小镜像大小
RUN apt clean && rm -rf /var/lib/apt/lists/*
# 添加 cron 任务
RUN echo "0 16 * * * cd /app && python cal_code/tick2trade.py >> /var/log/cron.log 2>&1" >> /etc/crontab
# 设置容器启动时默认执行的命令
CMD ["sh", "cal_code/start.sh"]
